package session

import (
	"bufio"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/ibrhajjaj/ig-dl/internal/types"
)

// WriteNetscape serialises the cookie jar inside s to the Netscape
// cookies.txt format, which is the lingua-franca both gallery-dl and
// yt-dlp accept via their --cookies flag. Output format (tab-separated,
// one cookie per line):
//
//	domain  flag  path  secure  expires  name  value
//
//   - domain:  the cookie's Domain field verbatim. httpOnly cookies get a
//     "#HttpOnly_" prefix in front of the domain, per curl/wget convention.
//   - flag:    "TRUE" when domain starts with "." (subdomain match),
//     "FALSE" otherwise.
//   - secure:  "TRUE"/"FALSE".
//   - expires: Unix epoch seconds, or "0" for session cookies (MaxAge < 0,
//     or no Expires set and MaxAge == 0).
//
// The file is written atomically by first creating a temp file in the
// same directory and renaming it on success; the parent directory is
// created with 0700 if missing and the final file is mode 0600.
func WriteNetscape(s *types.Session, path string) error {
	if s == nil {
		return errors.New("session: cannot write cookies from nil session")
	}
	dir := filepath.Dir(path)
	if dir == "" {
		dir = "."
	}
	if dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("session: create parent dir: %w", err)
		}
	}

	tmp, err := os.CreateTemp(dir, ".cookies-*.txt")
	if err != nil {
		return fmt.Errorf("session: create temp cookies file: %w", err)
	}
	tmpName := tmp.Name()
	// Best-effort cleanup if we bail before rename.
	defer func() { _ = os.Remove(tmpName) }()

	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("session: chmod temp file: %w", err)
	}

	w := bufio.NewWriter(tmp)
	if _, err := w.WriteString("# Netscape HTTP Cookie File\n"); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("session: write header: %w", err)
	}
	if _, err := w.WriteString("# https://curl.se/docs/http-cookies.html\n"); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("session: write header: %w", err)
	}
	if _, err := w.WriteString("# This file was generated by ig-dl. Do not edit.\n\n"); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("session: write header: %w", err)
	}

	for i := range s.Cookies {
		c := &s.Cookies[i]
		line := formatNetscapeLine(c.Domain, c.Path, c.Name, c.Value, c.Secure, c.HttpOnly, netscapeExpires(c))
		if _, err := w.WriteString(line); err != nil {
			_ = tmp.Close()
			return fmt.Errorf("session: write cookie line: %w", err)
		}
	}

	if err := w.Flush(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("session: flush cookies: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("session: close temp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("session: rename temp: %w", err)
	}
	return nil
}

// formatNetscapeLine builds a single cookie line in Netscape cookies.txt
// format, including the "#HttpOnly_" domain prefix when httpOnly is true.
// Exposed within the package so cookies_test.go can drive it directly and
// assert the exact formatting (flag + tabs) without going through a file.
func formatNetscapeLine(domain, path, name, value string, secure, httpOnly bool, expires int64) string {
	if path == "" {
		path = "/"
	}
	flag := "FALSE"
	if strings.HasPrefix(domain, ".") {
		flag = "TRUE"
	}
	sec := "FALSE"
	if secure {
		sec = "TRUE"
	}
	prefixed := domain
	if httpOnly {
		prefixed = "#HttpOnly_" + domain
	}
	return fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s\n",
		prefixed, flag, path, sec, expires, name, value)
}

// netscapeExpires renders an http.Cookie's expiration into the integer
// used by the Netscape format. Session cookies (no Expires and MaxAge
// == 0, or MaxAge < 0) encode as 0.
func netscapeExpires(c *http.Cookie) int64 {
	// MaxAge < 0 is the "delete me" / session marker.
	if c.MaxAge < 0 {
		return 0
	}
	if !c.Expires.IsZero() {
		return c.Expires.Unix()
	}
	// No expiry info at all → session cookie.
	return 0
}
